@startuml Singleton_SequenceDiagram
actor iMain
participant ":Singleton" as Singleton
iMain -> Singleton ++: getInstance( )
Singleton -> Singleton ++ : <<create>>
Singleton --
Singleton --
iMain -> Singleton: SingletonOperation( )
@enduml