#pragma once

#include "CHello.h"
#include "Solution1.h"
#include "Solution2.h"
#include "Solution3.h"
#include "Solution4.h"
#include "Solution5.h"
#include "Solution6.h"
#include "Solution7.h"
#include "Solution8.h"
#include "Solution9.h"
#include "Solution10.h"
#include "Solution11.h"
#include "Solution12.h"
#include "Solution13.h"
